[error] java.lang.RuntimeException: No main class detected.
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$4(Defaults.scala:1817)
[error] 	at sbt.Defaults$$$Lambda$4146/288314556.apply(Unknown Source)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$3(Defaults.scala:1817)
[error] 	at sbt.Defaults$$$Lambda$4070/188647125.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at scala.Function1$$Lambda$247/2102900382.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2402/1876259196.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2443/457985189.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2412/1227438915.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2425/1016090398.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error] 	at java.lang.Thread.run(Unknown Source)
[error] (Compile / bgRun) No main class detected.
